/**
 * The service worker (spec §14 "PWA"), generated at build time as dist/sw.js.
 *
 * - Versioned by a hash of everything the build ships (bundle file names,
 *   which carry content hashes, and the contents of public/), so any change
 *   installs a new worker whose activation drops the old caches.
 * - Pages are network-first: online, a deploy is always picked up; offline,
 *   the cached page starts. Hashed bundles (/assets/) are cache-first, which
 *   can never be stale since a new build has new names. Other files (models,
 *   textures, audio) are served from the cache and refreshed behind it.
 * - The engine and the assets the first room needs are precached on install;
 *   the rest (music, far rooms' sounds) is cached as it is first played.
 * - A new worker waits for open tabs to close instead of taking over a game
 *   in progress, so a running page never mixes two builds.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import type { Plugin } from 'vite';

/** Public files precached on install (the first room); everything else is cached on first use. */
export const PRECACHE_PUBLIC = [
  /^models\/.*\.glb$/,
  /^anim\/.*\.json$/,
  /^textures\//,
  /^levels\//,
  /^icons\//,
];

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) out.push(...walk(path));
    else out.push(path);
  }
  return out;
}

/** The worker's source for a version and its precache list (URLs relative to the worker). */
export function serviceWorkerSource(version: string, precache: readonly string[]): string {
  return `// Generated by scripts/vite-sw.ts. Do not edit.
const VERSION = ${JSON.stringify(version)};
const CACHE = 'nc-' + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('nc-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

const put = (request, response) => {
  if (response.ok && response.status === 200) {
    const copy = response.clone();
    caches.open(CACHE).then((c) => c.put(request, copy));
  }
  return response;
};

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || request.headers.has('range')) return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    // Network first: a deploy is never hidden behind the cache.
    event.respondWith(
      fetch(request)
        .then((r) => put(request, r))
        .catch(() => caches.match(request).then((r) => r || caches.match('./index.html'))),
    );
    return;
  }
  if (url.pathname.endsWith('/sw.js')) return;
  const hashed = url.pathname.includes('/assets/');
  event.respondWith(
    caches.match(request).then((cached) => {
      const network = fetch(request).then((r) => put(request, r));
      if (cached) {
        // Content-hashed bundles never change; other files refresh behind the cached copy.
        if (!hashed) event.waitUntil(network.catch(() => undefined));
        return cached;
      }
      return network;
    }),
  );
});
`;
}

/**
 * Critical assets the page asks for as soon as the HTML arrives, in parallel
 * with the engine's JavaScript, instead of after it has run.
 */
export const PRELOAD = [{ href: './models/nora.glb', as: 'fetch' }] as const;

/** Adds the preload links to index.html. */
export function preloadPlugin(): Plugin {
  return {
    name: 'ninth-chamber-preload',
    transformIndexHtml: () =>
      PRELOAD.map((p) => ({
        tag: 'link',
        attrs: { rel: 'preload', href: p.href, as: p.as, crossorigin: 'anonymous' },
        injectTo: 'head' as const,
      })),
  };
}

/** Emits sw.js with the build's version and precache list. */
export function serviceWorkerPlugin(root: string): Plugin {
  return {
    name: 'ninth-chamber-sw',
    apply: 'build',
    generateBundle(_options, bundle) {
      const publicDir = join(root, 'public');
      const files = walk(publicDir).map((p) => relative(publicDir, p).split(sep).join('/'));
      const hash = createHash('sha256');
      const built = Object.keys(bundle)
        .filter((f) => !f.endsWith('.map'))
        .sort();
      for (const f of built) hash.update(f);
      for (const f of files.sort()) hash.update(f).update(readFileSync(join(publicDir, f)));
      const version = hash.digest('hex').slice(0, 12);
      const precache = [
        './',
        ...built.filter((f) => f !== 'index.html' && !f.endsWith('.txt')).map((f) => `./${f}`),
        ...files.filter((f) => PRECACHE_PUBLIC.some((re) => re.test(f))).map((f) => `./${f}`),
      ];
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorkerSource(version, precache) });
    },
  };
}
